### ISSUE TITLE
How install native-client-npm ?

### ISSUE THREAD

**Issue by trimechee** [andy-portmen/native-client-npm#1]
Hello, after your advice to install Native-client-npm to add support for other web browsers in my windows 7 32 bits, I try to install and I expected to see a program in .exe form....

so if I understood correctly, we must first install the old Nodejs 13 compatible winth windows 7 32 bits then after open cmd and type:

npm install native-client
npm run install --prefix node_modules/native-client

i have windows 7 starter editon so i can't even make past in cmd with shorcuts CTRL+V.....

**Comment by andy-portmen** [comment]
Yes, if you can install an old version of NodeJS on your OS, you should be able to follow this guide.

**Comment by trimechee** [comment]
Great ! Thank you so much for your many help :)

**Comment by trimechee** [comment]
Please the guide means we open cmd as administrator, then we put in cmd : 

npm install native-client 

then we press ok then in cmd we copy paste:

 npm run install --prefix node_modules/native-client ?

there will be no conflict beatween native client npm and the classic natice client of Open-in-vlc?

For Open in vlc, I find there is unfair because the true full potential power of the extension is not revealed for people and it is believed that it is a copy of external extension button specific to vlc while the real power of Open-in-vlc is to detect complex hls video download media links, and I just tested, I can no longer download vidmoly video with the famous Live-stream-donwloader extension which will certainly fix the problem soon while Open-in -vlc, we can send the hls video to vlc so Open-in-vlc is the ultimate only reliable alternative to video downloaders !

**Comment by trimechee** [comment]
I tried installing via cmd: cmd displays this message: npm is not recognized as an internal or external command or executable program or batch file

**Comment by andy-portmen** [comment]
> there will be no conflict beatween native client npm and the classic natice client of Open-in-vlc?

They both do the same thing (this package does not include NodeJS in the directory, the old one does). There is no conflict, but there is no need to use two different methods.

**Comment by andy-portmen** [comment]
> npm is not recognized as an internal or external command or executable program or batch file

You need to install npm on your OS.

**Comment by trimechee** [comment]
Interesting, thank you!  it seems i should make account in npm website before maybe donwloading nmp, there is even paid version....
